fs: 48000
nfft: 96000
num: 20
output_data_path: "output/e0_minimal.pkl"
optimize: true
fdn_config:
  N: 8
  delay_range_ms: [10.0, 30.0]
  onset_time: [10]
  early_reflections_type: "FIR"
  drr: 0.25
  energy: 1.0
  alias_decay_db: 60
  attenuation_config:
    attenuation_type: 'geq'
    attenuation_range: [0.5, 3.5]
