fs: 48000
nfft: 96000
num: 1
output_data_path: "./output/aes25_experiments/GFDN/gfdn_rirs.pkl"
optimize: true
fdn_config:
  fdn_type: "gfdn"
  n_groups: 3
  N: 4
  delay_range_ms: [10.0, 50.0]
  onset_time: [10]
  drr: 0.25
  energy: 1.0
  optimize: False
  gain_init: "uniform"
  coupling_angles: [0.1, 0.20, 0.34]
  mixing_angles: [0.78, 0.78, 0.78]
  attenuation_config:
    attenuation_type: "geq"
    # attenuation_param: [[3.0], [0.8], [2.0]]
fdn_optim_config:
  train_dir: "./output/aes25_experiments/GFDN/training"
  max_epochs: 2